spring:
  application:
    name: turbine-stream
  profiles:
    active:
    - test  
    - uat
    
server:
  port: 8989
  
turbine:
  # metrics of services that needs to be shown with turbine
  app-config:  movie-catalog-service
  # creating a default cluster to be monitored in /turbine.stream
  # if we need to create a new cluster, the endpoint changes
  cluster-name-expression: new String("default")

management:
  endpoints:
    web:
      exposure:
        include: "*"

stream:
  app:
    list: movie-catalog-service, movie-info-service, rating-data-service
    description: "{ movieCatalogService: 'retrieves movie catalog', movieInfoService: 'retrieves movie information from TMDb', ratingsDataService: 'retrieves user ratings for movie id'}"

db:
  host: https://___
  username: db-user
  port: 1200
  schema: NEW_SCHEMA